# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the Euclidean distance matrix
#'
#' @param X matrix (tipically of N coordindates on \mathbb{R}^2 )
#'
#' @return distance matrix of the elements of X
#' @export
arma_dist <- function(X) {
    .Call(`_ASMK_arma_dist`, X)
}

#' Build a grid from two vector (i.e. equivalent to expand.grid() in R)
#'
#' @param x first vector of numeric elements
#' @param y second vector of numeric elements
#'
#' @return matrix as expanded grid of combinations
#'
expand_grid_cpp <- function(x, y) {
    .Call(`_ASMK_expand_grid_cpp`, x, y)
}

#' Function to sample integers (index)
#'
#' @param size dimension of the set to sample
#' @param length number of elements to sample
#' @param p vector of probabilities
#'
#' @return vector of sampled integers
#'
sample_index <- function(size, length, p) {
    .Call(`_ASMK_sample_index`, size, length, p)
}

#' Compute the parameters for the posteriors distribution of \beta and \Sigma (i.e. updated parameters)
#'
#' @param data two dimensional list: first named "Y", second named "X"
#' @param priors list with the priors: named "mu_B", "V_r", "a", "b"
#' @param coords matrix of sample coordinates for X and Y
#' @param hyperpar two dimensional list: first named "delta", second named "phi"
#'
#' @return list of posterior update parameters
#'
fit_cpp <- function(data, priors, coords, hyperpar) {
    .Call(`_ASMK_fit_cpp`, data, priors, coords, hyperpar)
}

#' Sample R draws from the posterior distributions
#'
#' @param poster the output from "fit_cpp" function
#' @param R number of posterior samples
#' @param par boolean, if TRUE only \beta and \sigma^2 are sampled (\omega is omitted)
#' @param p if par TRUE, it specifies the column number of X
#'
#' @return list of posterior samples
#'
post_draws <- function(poster, R = 50L, par = FALSE, p = 1L) {
    .Call(`_ASMK_post_draws`, poster, R, par, p)
}

#' Draw from the conditional posterior predictive for a set of unobserved covariates
#'
#' @param data ...
#' @param X_u ...
#' @param Rphi_s ...
#' @param d_u ...
#' @param d_us ...
#' @param hyperpar ...
#' @param poster ...
#'
#' @return list of posterior predictive samples
#'
r_pred_cpp <- function(data, X_u, Rphi_s, d_u, d_us, hyperpar, poster) {
    .Call(`_ASMK_r_pred_cpp`, data, X_u, Rphi_s, d_u, d_us, hyperpar, poster)
}

#' Evaluate the density of a set of unobserved response with respect to the conditional posterior predictive
#'
#' @param data ...
#' @param X_u ...
#' @param Y_u ...
#' @param Rphi_s ...
#' @param d_u ...
#' @param d_us ...
#' @param hyperpar ...
#' @param poster ...
#'
#' @return vec of posterior predictive density evaluations
#'
d_pred_cpp <- function(data, X_u, Y_u, Rphi_s, d_u, d_us, hyperpar, poster) {
    .Call(`_ASMK_d_pred_cpp`, data, X_u, Y_u, Rphi_s, d_u, d_us, hyperpar, poster)
}

#' Compute the LOOCV of the density evaluations for fixed values of the hyperparameters
#'
#' @param data ...
#' @param priors ...
#' @param coords ...
#' @param hyperpar ...
#'
#' @return vec of posterior predictive density evaluations
#'
dens_loocv <- function(data, priors, coords, hyperpar) {
    .Call(`_ASMK_dens_loocv`, data, priors, coords, hyperpar)
}

#' Compute the KCV of the density evaluations for fixed values of the hyperparameters
#'
#' @param data ...
#' @param priors ...
#' @param coords ...
#' @param hyperpar ...
#' @param K ...
#'
#' @return vec of posterior predictive density evaluations
#'
dens_kcv <- function(data, priors, coords, hyperpar, K) {
    .Call(`_ASMK_dens_kcv`, data, priors, coords, hyperpar, K)
}

#' Return the CV predictive density evaluations for all the model combinations
#'
#' @param data ...
#' @param priors ...
#' @param coords ...
#' @param hyperpar ...
#' @param useKCV ...
#' @param K ...
#'
#' @return matrix of posterior predictive density evaluations, each columns represent a different model
#'
models_dens <- function(data, priors, coords, hyperpar, useKCV, K = 10L) {
    .Call(`_ASMK_models_dens`, data, priors, coords, hyperpar, useKCV, K)
}

#' Compute the KCV of the density evaluations for fixed values of the hyperparameters
#'
#' @param data ...
#' @param priors ...
#' @param coords ...
#' @param hyperpar ...
#' @param K ...
#'
#' @return list of posterior predictive density evaluations
#'
dens_kcv2 <- function(data, priors, coords, hyperpar, K) {
    .Call(`_ASMK_dens_kcv2`, data, priors, coords, hyperpar, K)
}

#' Return the CV predictive density evaluations for all the model combinations
#'
#' @param data ...
#' @param priors ...
#' @param coords ...
#' @param hyperpar ...
#' @param K ...
#'
#' @return matrix of posterior predictive density evaluations, each columns represent a different model
#'
models_dens2 <- function(data, priors, coords, hyperpar, K = 10L) {
    .Call(`_ASMK_models_dens2`, data, priors, coords, hyperpar, K)
}

#' Compute the BPS spatial prediction given a set of stacking weights
#'
#' @param data ...
#' @param X_u ...
#' @param priors ...
#' @param coords ...
#' @param crd_u ...
#' @param hyperpar ...
#' @param W ...
#' @param R ...
#'
#' @return list of BPS posterior predictive samples
#' @export
BPS_SpatialPrediction_cpp <- function(data, X_u, priors, coords, crd_u, hyperpar, W, R) {
    .Call(`_ASMK_BPS_SpatialPrediction_cpp`, data, X_u, priors, coords, crd_u, hyperpar, W, R)
}

#' Compute the BPS posterior samples given a set of stacking weights
#'
#' @param data ...
#' @param priors ...
#' @param coords ...
#' @param hyperpar ...
#' @param W ...
#' @param R ...
#'
#' @return ...
#' @export
BPS_post_draws <- function(data, priors, coords, hyperpar, W, R) {
    .Call(`_ASMK_BPS_post_draws`, data, priors, coords, hyperpar, W, R)
}

#' Compute the parameters for the posteriors distribution of \beta and \Sigma (i.e. updated parameters)
#'
#' @param data two dimensional list: first named "Y", second named "X"
#' @param priors list with the priors: named "mu_B", "V_r", "a", "b"
#' @param coords matrix of sample coordinates for X and Y
#' @param hyperpar two dimensional list: first named "delta", second named "phi"
#'
#' @return list of posterior update parameters
#'
fit_latent_cpp <- function(data, priors, coords, hyperpar) {
    .Call(`_ASMK_fit_latent_cpp`, data, priors, coords, hyperpar)
}

#' The same fit_latent_cpp, but take as argument the distance matrix directly (does not compute it by itself from coords)
#'
#' @param data two dimensional list: first named "Y", second named "X"
#' @param priors list with the priors: named "mu_B", "V_r", "a", "b"
#' @param coords matrix of sample coordinates for X and Y
#' @param hyperpar two dimensional list: first named "delta", second named "phi"
#'
#' @return list of posterior update parameters
#'
fit_latent_cpp2 <- function(data, priors, dist, hyperpar) {
    .Call(`_ASMK_fit_latent_cpp2`, data, priors, dist, hyperpar)
}

#' Sample R draws from the posterior distributions
#'
#' @param poster the output from "fit_cpp" function
#' @param R number of posterior samples
#' @param par boolean, if TRUE only \beta and \sigma^2 are sampled (\omega is omitted)
#' @param p if par TRUE, it specifies the column number of X
#'
#' @return list of posterior samples
#'
post_draws_latent <- function(poster, R = 50L, par = FALSE, p = 2L) {
    .Call(`_ASMK_post_draws_latent`, poster, R, par, p)
}

#' Compute the BPS posterior samples given a set of stacking weights
#'
#' @param data ...
#' @param priors ...
#' @param coords ...
#' @param hyperpar ...
#' @param W ...
#' @param R ...
#'
#' @return ...
#' @export
BPS_post_draws_latent <- function(data, priors, coords, hyperpar, W, R) {
    .Call(`_ASMK_BPS_post_draws_latent`, data, priors, coords, hyperpar, W, R)
}

#' Draw from the conditional posterior predictive for a set of unobserved covariates
#'
#' @param data ...
#' @param X_u ...
#' @param d_u ...
#' @param d_us ...
#' @param hyperpar ...
#' @param poster ...
#' @param beta ...
#' @param sigma ...
#'
#' @return list of posterior predictive samples
#'
r_pred_latent_cpp <- function(data, X_u, d_u, d_us, hyperpar, poster, beta, sigma) {
    .Call(`_ASMK_r_pred_latent_cpp`, data, X_u, d_u, d_us, hyperpar, poster, beta, sigma)
}

#' Evaluate the density of a set of unobserved response with respect to the conditional posterior predictive
#'
#' @param data ...
#' @param X_u ...
#' @param Y_u ...
#' @param d_u ...
#' @param d_us ...
#' @param hyperpar ...
#' @param poster ...
#' @param beta ...
#' @param sigma ...
#'
#' @return posterior predictive density evaluation (double)
#'
d_pred_latent_cpp <- function(data, X_u, Y_u, d_u, d_us, hyperpar, poster, beta, sigma) {
    .Call(`_ASMK_d_pred_latent_cpp`, data, X_u, Y_u, d_u, d_us, hyperpar, poster, beta, sigma)
}

#' Compute the LOOCV of the density evaluations for fixed values of the hyperparameters
#'
#' @param data ...
#' @param priors ...
#' @param coords ...
#' @param hyperpar ...
#'
#' @return vec of posterior predictive density evaluations
#'
dens_loocv_latent <- function(data, priors, coords, hyperpar) {
    .Call(`_ASMK_dens_loocv_latent`, data, priors, coords, hyperpar)
}

#' Compute the KCV of the density evaluations for fixed values of the hyperparameters
#'
#' @param data ...
#' @param priors ...
#' @param coords ...
#' @param hyperpar ...
#' @param K ...
#'
#' @return vec of posterior predictive density evaluations
#'
dens_kcv_latent <- function(data, priors, coords, hyperpar, K) {
    .Call(`_ASMK_dens_kcv_latent`, data, priors, coords, hyperpar, K)
}

#' Return the CV predictive density evaluations for all the model combinations
#'
#' @param data ...
#' @param priors ...
#' @param coords ...
#' @param hyperpar ...
#' @param useKCV ...
#' @param K ...
#'
#' @return matrix of posterior predictive density evaluations, each columns represent a different model
#'
models_dens_latent <- function(data, priors, coords, hyperpar, useKCV, K = 10L) {
    .Call(`_ASMK_models_dens_latent`, data, priors, coords, hyperpar, useKCV, K)
}

#' Compute the BPS spatial prediction given a set of stacking weights
#'
#' @param data ...
#' @param X_u ...
#' @param priors ...
#' @param coords ...
#' @param crd_u ...
#' @param hyperpar ...
#' @param W ...
#' @param R ...
#'
#' @return list of BPS posterior predictive samples
#' @export
BPS_latent_SpatialPrediction_cpp <- function(data, X_u, priors, coords, crd_u, hyperpar, W, R) {
    .Call(`_ASMK_BPS_latent_SpatialPrediction_cpp`, data, X_u, priors, coords, crd_u, hyperpar, W, R)
}

